spring:
  application:
    name: Callback Handler
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/callbacks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:pat1}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  security:
    user:
      name: ${SS_USERNAME:user}
      password: ${SS_PASSWORD:$2a$12$mpLQxrD2NJUPdQKUdkbVwOHs9fBwTC2owGOLIsXgBAOM6OieTfhNO}