spring:
  application:
    name: Callback Handler
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:callbacks}
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: ${SS_USERNAME:user}
      password: ${SS_PASSWORD:$2a$12$mpLQxrD2NJUPdQKUdkbVwOHs9fBwTC2owGOLIsXgBAOM6OieTfhNO}